"""empty message

Revision ID: 282879650c14
Revises: 
Create Date: 2026-04-09 17:11:44.287688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282879650c14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_profiles',
    sa.Column('m_id', sa.Integer(), nullable=False),
    sa.Column('m_title', sa.String(length=80), nullable=False),
    sa.Column('m_desc', sa.Text(), nullable=False),
    sa.Column('m_poster', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('m_id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('movie_profiles')
    # ### end Alembic commands ###
